### ISSUE TITLE
Have you tried the same with Vite

### ISSUE THREAD

**Issue by dubzzz** [mmazzarolo/tangerine-monorepo#5]
Hello,

This repository is fabulous. I used it to speed-up my build-chain. It works as charm.

I was just wondering if you already tried to apply the pattern with vite too?
Vite being backed by esbuild+rollup you may have tried it 🤔 

So far when trying the setup with vite I get:
```txt
[vite]: Rollup failed to resolve import "@myrepo/mypackage/src/Compo" from "src\App.tsx".
```

Anyway, mostly asking in case you did.
Feel free to close the issue if you don't have anything in mind for vite.

Once again, thanks a lot ❤️

**Comment by mmazzarolo** [comment]
Hey @dubzzz , thanks for the kind words :)
Nope, I haven't had a chance to integrate it with Vite yet :/

**Comment by dubzzz** [comment]
For vite, I found a way to make it work by defining a `resolve.alias` like:
```ts
{ find: '@myorg', replacement: path.join(__dirname, '..', 'src'), },
```
